name: Test that the site builds

on: [push, pull_request]

permissions:
  contents: write # To push a preview to gh pages
  pull-requests: write # To comment on the PR

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - run: npm test

      - name: Deploy Preview
        # Only run this job if the repository is NOT a fork and the actor is not dependabot or renovate
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && !(github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]') }}
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: out
          target-folder: preview/preview/preview/${{github.event.number}}
      - name: Comment about preview
        # Only run this job if the repository is NOT a fork and the actor is not dependabot or renovate
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && !(github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]') }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview this PR: https://custom-elements-everywhere.com/preview/preview/preview/${{github.event.number}}/
